### ISSUE TITLE
The result is not matched with paper.

### ISSUE THREAD

**Issue by danbo6** [leejoonhun/factor-vae#1]
Hi, really appreciate your work on implementation of this paper! But I found there are some issues to achieve the similiar result with the original paper. I'm wondering if you met the same issue?

Thanks

**Comment by leejoonhun** [comment]
Hi, thanks for your interest in my FactorVAE implementation.

First, I want to clarify that this implementation is for implementing FactorVAE as described in the paper, not for reproducing the exact results of the paper.
There are some differences in the model and experiments, as I do not know what specific implementation the authors used (e.g. version, seed).

I have implemented this code to the best of my ability, but please let me know if you encounter any problems running the experiments or implementation.
